main: net.horizonsend.discordbridge.DiscordBridge
name: DiscordBridge
version: 1.0.0
description: A minecraft chat link which automatically syncs mutes and bans.
api-version: 1.17
load: POSTWORLD
author: PeterCrawley
website: https://horizonsend.net
depend: [Essentials, LuckPerms]
commands:
  link:
    description: Link your discord account to your minecraft account.
    usage: /<command> <discord>